language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.11.2
cache:
  - bundler
addons:
  code_climate:
    repo_token: f04193803b076f62ec5b0b5d5367e4e2cadd156303b0e90aebd7fa4c504d177e
